language: node_js
node_js:
  - "10"
notifications:
  email:
    on_success: never
script: npm test && npm run lib

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
